var db = require("./models");
const mongoose = require('mongoose');

var weaponList = [
  {
    name: 'L85A2',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Assult Rifle',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight','ACOG Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Muzzle Brake'],
    grips: ['Vertical Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('L85A2assultr'),
  },
  {
    name: 'FMG-9',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Reflex Sight',],
    barrels: ['Suppressor','Flash Hider','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('fmg900000000'),
  },
  {
    name: 'M590A1',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Pump-Action'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('M590A1000000'),
  },
  {
    name: 'P226 Mk 25',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('p226mk250000'),
  },
  {
    name: 'SMG-11',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['automatic'],
    type: 'Machine Pistol',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Extended Barrel'],
    grips: ['Vertical Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('SMG110000000'),
  },
  {
    name: 'MP5K',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic', '3-round burst', 'Semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('MP5K00000000'),
  },
  {
    name: 'UMP45',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic', '3-round Burst'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Muzzle Brake', 'Extended Barrrel'],
    grips: ['Vertical Grip', 'Angled Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('UMP450000000'),
  },
  {
    name: 'M1014',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Semi-automatic'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('M10140000000'),
  },
  {
    name: '5.7 USG',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('57usg0000000'),
  },
  {
    name: 'M45 MEUSOC',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('M45MEUSOC000'),
  },

]

db.Weapon.remove({},(err, weapon) =>{
    db.Weapon.create(weaponList, (err, weapons) =>{
      if (err) { return console.log('ERROR', err); }
      console.log("created", weapons.length);
      process.exit();
    });
  });