var db = require("./models");
const mongoose = require('mongoose');

var weaponList = [
  {
    name: 'L85A2',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Assult Rifle',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight','ACOG Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Muzzle Brake'],
    grips: ['Vertical Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('L85A2assultr'),
  },
  {
    name: 'FMG-9',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Reflex Sight',],
    barrels: ['Suppressor','Flash Hider','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('fmg900000000'),
  },
  {
    name: 'M590A1',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Pump-Action'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('M590A1000000'),
  },
  {
    name: 'P226 Mk 25',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('p226mk250000'),
  },
  {
    name: 'SMG-11',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['automatic'],
    type: 'Machine Pistol',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Extended Barrel'],
    grips: ['Vertical Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('SMG110000000'),
  },
  {
    name: 'MP5K',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic', '3-round burst', 'Semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('MP5K00000000'),
  },
  {
    name: 'UMP45',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic', '3-round Burst'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Muzzle Brake', 'Extended Barrrel'],
    grips: ['Vertical Grip', 'Angled Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('UMP450000000'),
  },
  {
    name: 'M1014',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Semi-automatic'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('M10140000000'),
  },
  {
    name: '5.7 USG',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('57usg0000000'),
  },
  {
    name: 'M45 MEUSOC',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('M45MEUSOC000'),
  },
  {
    name: 'SG-CQB',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Pump-action'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: ['Vertical Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('SGCQB0000000'),
  },
  {
    name: 'MP5',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic', '3-round Burst'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight','ACOG Sight'],
    barrels: ['Suppressor','Flash Hider','Muzzle Brake'],
    grips: ['Vertical Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('MP5000000000'),
  },
  {
    name: 'P90',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight','ACOG Sight'],
    barrels: ['Suppressor','Flash Hider','Muzzle Brake','Extended Barrel'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('P9O000000000'),
  },
  {
    name: 'P9',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('P90000000000'),
  },
  {
    name: 'LFP586',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['Double-action'],
    type: 'Handgun',
    sights: [],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('LFP586000000'),
  },
  {
    name: '9×19VSN',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Muzzle Brake','Compensator'],
    grips: ['Vertical Grip', 'Anled Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('9X19VSN00000'),
  },
  {
    name: 'SASG-12',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Semi-Automatic'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppessor'],
    grips: ['Vertical Grip','Angled Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('SASG12000000'),
  },
  {
    name: 'PMM',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('PMM000000000'),
  },
  {
    name: 'Gsh-18',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('GSH180000000'),
  },
  {
    name: 'M870',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Pump-action'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('M87000000000'),
  },
  {
    name: '416-C Carbine',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Assult Rifle',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Compensator','Muzzle Brake','Extended Barrel'],
    grips: ['Vertical Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('416CCARBINE0'),
  },
  {
    name: 'P12',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('P12000000000'),
  },
  {
    name: 'MP7',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Muzzle Brake','Compensator'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('MP7000000000'),
  },
  {
    name: 'Super 90',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Semi-Automatic'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('SUPER9000000'),
  },
  {
    name: '9mm C1',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Reflex Sight'],
    barrels: ['Suppressor','Extended Barrel'],
    grips: ['Angled Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('9MMC10000000'),
  },
  {
    name: 'Mk1 9mm',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: ['Suppressor','Muzzle Brake'],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('MK19MM000000'),
  },
  {
    name: 'MPX',
    img: '/na',
    assignment: 'primary',
    firemodes: ['automatic','semi-automatic'],
    type: 'Submachine Gun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: ['Suppressor','Flash Hider','Muzzle Brake','Compensator'],
    grips: ['Vertical Grip','Angled Grip'],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('MPX000000000'),
  },
  {
    name: 'SPAS-12',
    img: '/na',
    assignment: 'primary',
    firemodes: ['Semi-Automatic'],
    type: 'Shotgun',
    sights: ['Red Dot Sight','Holographic Sight','Reflex Sight'],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('SPAS12000000'),
  },
  {
    name: 'D-50',
    img: '/na',
    assignment: 'secondary',
    firemodes: ['semi-automatic'],
    type: 'Handgun',
    sights: [],
    barrels: [],
    grips: [],
    underbarrel: ['Lazer'],
    _id: mongoose.Types.ObjectId('D50000000000'),
  },

]

db.Weapon.remove({},(err, weapon) =>{
    db.Weapon.create(weaponList, (err, weapons) =>{
      if (err) { return console.log('ERROR', err); }
      console.log("created", weapons.length);
      process.exit();
    });
  });