const mongoose = require('mongoose');

module.exports = {
  weaponList: [
    {
      name: 'L85A2',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('L85A2assultr'),
    },
    {
      name: 'FMG-9',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight', ],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('fmg900000000'),
    },
    {
      name: 'M590A1',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Pump-Action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('M590A1000000'),
    },
    {
      name: 'P226 Mk 25',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('p226mk250000'),
    },
    {
      name: 'SMG-11',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['automatic'],
      type: 'Machine Pistol',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Extended Barrel'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SMG110000000'),
    },
    {
      name: 'MP5K',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', '3-round burst', 'Semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MP5K00000000'),
    },
    {
      name: 'UMP45',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic', '3-round Burst'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake', 'Extended Barrrel'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('UMP450000000'),
    },
    {
      name: 'M1014',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Semi-automatic'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('M10140000000'),
    },
    {
      name: '5.7 USG',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('57usg0000000'),
    },
    {
      name: 'M45 MEUSOC',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('M45MEUSOC000'),
    },
    {
      name: 'SG-CQB',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Pump-action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SGCQB0000000'),
    },
    {
      name: 'MP5',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic', '3-round Burst'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MP5000000000'),
    },
    {
      name: 'P90',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Extended Barrel'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('P9O000000000'),
    },
    {
      name: 'P9',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('P90000000000'),
    },
    {
      name: 'LFP586',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['Double-action'],
      type: 'Handgun',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('LFP586000000'),
    },
    {
      name: '9×19VSN',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Compensator'],
      grips: ['Vertical Grip', 'Anled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('9X19VSN00000'),
    },
    {
      name: 'SASG-12',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Semi-Automatic'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppessor'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SASG12000000'),
    },
    {
      name: 'PMM',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('PMM000000000'),
    },
    {
      name: 'Gsh-18',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('GSH180000000'),
    },
    {
      name: 'M870',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Pump-action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('M87000000000'),
    },
    {
      name: '416-C Carbine',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake', 'Extended Barrel'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('416CCARBINE0'),
    },
    {
      name: 'P12',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('P12000000000'),
    },
    {
      name: 'MP7',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Compensator'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MP7000000000'),
    },
    {
      name: 'Super 90',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Semi-Automatic'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SUPER9000000'),
    },
    {
      name: '9mm C1',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Extended Barrel'],
      grips: ['Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('9MMC10000000'),
    },
    {
      name: 'Mk1 9mm',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MK19MM000000'),
    },
    {
      name: 'MPX',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Compensator'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MPX000000000'),
    },
    {
      name: 'SPAS-12',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Semi-Automatic'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SPAS12000000'),
    },
    {
      name: 'D-50',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('D50000000000'),
    },
    {
      name: 'M12',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Extended Barrel'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('M12000000000'),
    },
    {
      name: 'SPAS-15',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Semi-Automatic'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SPAS15000000'),
    },
    {
      name: '"Luison"',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('LUISON000000'),
    },
    {
      name: 'ALDA 5.56',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic'],
      type: 'Light Machine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('ALDA55600000'),
    },
    {
      name: 'ACS12',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('ACS120000000'),
    },
    {
      name: '"Bailiff 410"',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['Double-action'],
      type: 'Handgun',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('BAILIFF41000'),
    },
    {
      name: '"Keratos .357"',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['Double-action'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('KERATOS35700'),
    },
    {
      name: 'Mx4 Storm',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight', 'Holographic Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Extended Barrel', 'Compensator'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MX4STORM0000'),
    },
    {
      name: 'SMG-12',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['automatic'],
      type: 'Machine Pistol',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SMG120000000'),
    },
    {
      name: 'K1A',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic', '3-round burst'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight', 'Holographic Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Compensator'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('K1A000000000'),
    },
    {
      name: 'BOSG.12.2',
      img: '/na',
      assignment: 'primary',
      firemodes: ['break-action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('BOSG12200000'),
    },
    {
      name: 'C75 Auto',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Machine Pistol',
      sights: [],
      barrels: ['Suppressor'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('C75AUTO00000'),
    },
    {
      name: 'Scorpion EVO 3 A1',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight', 'Holographic Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Compensator'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SCORPIONEVO3'),
    },
    {
      name: 'FO-12',
      img: '/na',
      assignment: 'primary',
      firemodes: ['break-action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Extended Barrel'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('FO1200000000'),
    },
    {
      name: '"RG15"',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('RG1500000000'),
    },
    {
      name: 'SIX12 SD',
      img: '/na',
      assignment: 'primary',
      firemodes: ['double-action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SIX12SD00000'),
    },
    {
      name: 'T-5 SMG',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight', 'Holographic Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Compensator'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('T5SMG0000000'),
    },
    {
      name: '"Q-929"',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('Q92900000000'),
    },
    {
      name: 'Vector .45 ACP',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic', '2-round burst'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight', 'Holographic Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake', 'Compensator'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('VECTOR45ACP0'),
    },
    {
      name: 'ITA12L',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Pump-Action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('ITA12L000000'),
    },
    {
      name: 'ITA12S',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['Pump-Action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('ITA12S000000'),
    },
    {
      name: '"USP40"',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('USP400000000'),
    },
    {
      name: 'SuperNova',
      img: '/na',
      assignment: 'primary',
      firemodes: ['Pump-Action'],
      type: 'Shotgun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: [],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SUPERNOVA000'),
    },
    {
      name: 'MP5SD',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Submachine Gun',
      sights: ['Red Dot Sight', 'Reflex Sight', 'Holographic Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake'],
      grips: ['Vertical Grip', 'Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MP5SD0000000'),
    },
    {
      name: 'P229',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('P22900000000'),
    },
    {
      name: 'Bearing 9',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['automatic'],
      type: 'Machine Pistol',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('BEARING90000'),
    },
    {
      name: 'CCE Shield',
      img: '/na',
      assignment: 'primary',
      firemodes: [],
      type: 'Balistic Shield',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: [],
      _id: mongoose.Types.ObjectId('CCESHIELD000'),
    },
    {
      name: 'P-10C',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['semi-automatic'],
      type: 'Handgun',
      sights: [],
      barrels: ['Suppressor', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('P10C00000000'),
    },
    {
      name: 'SPSMG9',
      img: '/na',
      assignment: 'secondary',
      firemodes: ['2-round Burst'],
      type: 'Machine Pistol',
      sights: [],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SPSMG9000000'),
    },
    {
      name: 'AR33',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic','2-round burst'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip','Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('AR3300000000'),
    },
    {
      name: '556xi',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip','Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('556XI0000000'),
    },
    {
      name: 'G36C',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip','Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('G36C00000000'),
    },
    {
      name: 'R4-C',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake','Extended Barrel'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('R4C000000000'),
    },
    {
      name: '417',
      img: '/na',
      assignment: 'primary',
      firemodes: ['semi-automatic'],
      type: 'Marksmen Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight','ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('417000000000'),
    },
    {
      name: 'F2',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic','3-round burst'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('F20000000000'),
    },
    {
      name: 'Extendable Shield',
      img: '/na',
      assignment: 'primary',
      firemodes: [],
      type: 'Balistic Shield',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: [],
      _id: mongoose.Types.ObjectId('EXTENDABLESH'),
    },
    {
      name: 'OTs-03',
      img: '/na',
      assignment: 'primary',
      firemodes: ['semi-automatic'],
      type: 'Marksmen Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight','Reflex Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Muzzle Brake'],
      grips: [],
      underbarrel: [],
      _id: mongoose.Types.ObjectId('OTS030000000'),
    },
    {
      name: 'Balistic Shield',
      img: '/na',
      assignment: 'primary',
      firemodes: [],
      type: 'Balistic Shield',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: [],
      _id: mongoose.Types.ObjectId('BALISTICSHIE'),
    },
    {
      name: '6P41',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic'],
      type: 'Light Machine Gun',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('6P4100000000'),
    },
    {
      name: 'AK-12',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic','3-round Burst'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip','Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('AK1200000000'),
    },
    {
      name: 'Flash Shield',
      img: '/na',
      assignment: 'primary',
      firemodes: [],
      type: 'Balistic Shield',
      sights: [],
      barrels: [],
      grips: [],
      underbarrel: [],
      _id: mongoose.Types.ObjectId('FLASHSHIELD0'),
    },
    {
      name: 'AUG A2',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('AUGA20000000'),
    },
    {
      name: '552 Commando',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic','3-round Burst'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip','Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('552COMMANDO0'),
    },
    {
      name: 'C8-SFW',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic','2-round burst'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake','Extended Barrel'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('C8SFW0000000'),
    },
    {
      name: 'CAMRS',
      img: '/na',
      assignment: 'primary',
      firemodes: ['semi-automatic'],
      type: 'Marksmen Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight','Reflex Sight','ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: [],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('CAMRS0000000'),
    },
    {
      name: 'MK17 CQB',
      img: '/na',
      assignment: 'primary',
      firemodes: ['automatic', 'semi-automatic'],
      type: 'Assult Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight', 'Reflex Sight', 'ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake','Extended Barrel'],
      grips: ['Vertical Grip','Angled Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('MK17CQB00000'),
    },
    {
      name: 'SR-25',
      img: '/na',
      assignment: 'primary',
      firemodes: ['semi-automatic'],
      type: 'Marksmen Rifle',
      sights: ['Red Dot Sight', 'Holographic Sight','Reflex Sight','ACOG Sight'],
      barrels: ['Suppressor', 'Flash Hider', 'Compensator', 'Muzzle Brake'],
      grips: ['Vertical Grip'],
      underbarrel: ['Lazer'],
      _id: mongoose.Types.ObjectId('SR2500000000'),
    },
  ]
}